### ISSUE TITLE
actividad2_ejercicios

### ISSUE THREAD

**Issue by elisa1223** [SistemasTecTlaxiaco/actividad-2-ejercicios-equipo-nestor-diego-elisa#2]
[SISTEMAS_NUMERICOS.pdf](https://github.com/SistemasTecTlaxiaco/actividad-2-ejercicios-equipo-nestor-diego-elisa/files/12555522/SISTEMAS_NUMERICOS.pdf)

**Comment by carla1131** [comment]
portada: 22%
procedimiento: 22%
figuras,ilustraciones y fotografías: 17%
resultado y conclucion: 22%
calificación: 16.6/20
evaluado por Maritza y Carla

**Comment by josealfredo79** [comment]
Bien hecho y revisado
